/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import Modelo1.GestionUsuario;
import Modelo1.Perfil;
import Modelo1.Conexion;
import controlador.NuevoUsuarioController;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import controlador.PrincipalController;
import java.sql.ResultSet;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;

/**
 *
 * @author Antony
 */
public class VentanaNuevoUsuario extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarUsuario
     */
    public VentanaNuevoUsuario() {

        initComponents();
        ArrayList<Perfil> perfilcaga = GestionUsuario.MostrarPerfil();
        for (Perfil p : perfilcaga) {

            jcbx_perfil.addItem(p.getId_perfil() + " " + p.getNombre_perfil());
        }
        jLabel13.setEnabled(false);
    }

    public void HabilitarButton() {
        if (!jtxt_nombreUsuario.getText().isEmpty() && !jtxt_apellidoUsuario.getText().isEmpty()
                && !jtxt_correoUsuario.getText().isEmpty() && !jtxt_Usuario.getText().isEmpty()
                && !jtxt_contrasena.getText().isEmpty() && !jtxt_dniUsuario.getText().isEmpty()
                && !jtxt_telefonoUsuario.getText().isEmpty() && !jtxt_dniUsuario.getText().isEmpty()) {
            jLabel13.setEnabled(true);
        } else {
            jLabel13.setEnabled(false);
        }
    }

    // NuevoUsuarioController regusu = new NuevoUsuarioController();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtxt_nombreUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxt_apellidoUsuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxt_telefonoUsuario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtxt_correoUsuario = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtxt_dniUsuario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxt_Usuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxt_contrasena = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jcbx_perfil = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Registrar Usuario");

        jLabel1.setText("Nombre:");

        jtxt_nombreUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_nombreUsuarioKeyTyped(evt);
            }
        });

        jLabel4.setText("Apellido: ");

        jtxt_apellidoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_apellidoUsuarioKeyTyped(evt);
            }
        });

        jLabel8.setText("Telefono:");

        jtxt_telefonoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_telefonoUsuarioKeyTyped(evt);
            }
        });

        jLabel9.setText("Correo:");

        jtxt_correoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_correoUsuarioKeyTyped(evt);
            }
        });

        jLabel15.setText("DNI:");

        jtxt_dniUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_dniUsuarioKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Cuenta ");

        jLabel6.setText("Usuario:");

        jtxt_Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_UsuarioKeyTyped(evt);
            }
        });

        jLabel7.setText("Contraseña:");

        jtxt_contrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_contrasenaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_apellidoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxt_correoUsuario)
                            .addComponent(jtxt_dniUsuario)
                            .addComponent(jtxt_telefonoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxt_nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(37, 37, 37)
                                .addComponent(jtxt_Usuario))
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jtxt_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxt_nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jtxt_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxt_apellidoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtxt_telefonoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jtxt_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtxt_correoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jtxt_dniUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Selecciona tu Perfil:");

        jcbx_perfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Perfil" }));
        jcbx_perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbx_perfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jcbx_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbx_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jLabel12.setText("Minimizar");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disquete.png"))); // NOI18N
        jLabel13.setText("Guardar");
        jLabel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jLabel11.setText("Atras");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-sesion.png"))); // NOI18N
        jLabel14.setText("Cerrar");
        jLabel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jButton1)
                    .addComponent(jLabel13))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        NuevoUsuarioController.botonSalir();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        NuevoUsuarioController.botonMinimizar();
    }//GEN-LAST:event_jLabel12MouseClicked
    private static String encriptarContraseña(String contraseña) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            byte[] hash = md.digest(contraseña.getBytes());
            StringBuilder sb = new StringBuilder();
            for (byte b : hash) {
                sb.append(String.format("%02x", b));
            }
            return sb.toString();
        } catch (NoSuchAlgorithmException e) {
            return null;
        }
    }

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:

        String nombre = jtxt_nombreUsuario.getText();
        String apellido = jtxt_apellidoUsuario.getText();
        String correo = jtxt_correoUsuario.getText();
        String usuario = jtxt_Usuario.getText();
        String contrasena = jtxt_contrasena.getText();
        String contraseñaEncriptada = encriptarContraseña(contrasena);
        int dni_usuario = Integer.parseInt(jtxt_dniUsuario.getText());
        int telefono = Integer.parseInt(jtxt_telefonoUsuario.getText());
        ResultSet rs;
        int perf = 0;
        if (jcbx_perfil.getSelectedIndex() != 0 || jcbx_perfil.getSelectedItem() != null) {
            perf = Integer.parseInt(String.valueOf(jcbx_perfil.getSelectedItem()).trim().split(" ")[0]);

        }
        //System.out.println("esa ".);
        try {
            Connection con = Conexion.getConexion();

            PreparedStatement ps = con.prepareStatement("INSERT INTO USUARIOS(usuario,contrasena,dni_usuario,correo,nombre,apellido,telefono, id_perfil) VALUES (?,?,?,?,?,?,?,?)");
            ps.setString(1, usuario);
            ps.setString(2, contraseñaEncriptada);
            ps.setInt(3, dni_usuario);
            ps.setString(4, correo);
            ps.setString(5, nombre);
            ps.setString(6, apellido);
            ps.setInt(7, telefono);
            ps.setInt(8, perf);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "REGISTRO GUARDADO...");
            limpiarRegistroUsuario();
            //cargartabla();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        PrincipalController.Mostrar();
        NuevoUsuarioController.Ocultar();


    }//GEN-LAST:event_jLabel11MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nombre = jtxt_nombreUsuario.getText();
        String apellido = jtxt_apellidoUsuario.getText();
        String correo = jtxt_correoUsuario.getText();
        String usuario = jtxt_Usuario.getText();
        String contrasena = jtxt_contrasena.getText();
        int dni_usuario = Integer.parseInt(jtxt_dniUsuario.getText());
        int telefono = Integer.parseInt(jtxt_telefonoUsuario.getText());

        try {
            Connection con = Conexion.getConexion();

            PreparedStatement ps = con.prepareStatement("UPDATE USUARIOS SET usuario='" + usuario + "', contrasena='" + contrasena + "', dni_usuario=" + dni_usuario + ", correo='" + correo + "', nombre='" + nombre + "', apellido='" + apellido + "', telefono=" + telefono + " WHERE dni_usuario=" + dni_usuario);
//             ps.setString(1, usuario);
//             ps.setString(2, contrasena);
//             ps.setInt(3,dni_usuario );
//             ps.setString(4, correo);
//             ps.setString(5, nombre);
//             ps.setString(6,apellido);
//             ps.setInt(7,telefono );
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "REGISTRO ACTUALIZADO...");
            limpiarRegistroUsuario();
            //cargartabla();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcbx_perfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbx_perfilActionPerformed

        if (jcbx_perfil.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Sebe seleccionar un Perfil.");
        }

    }//GEN-LAST:event_jcbx_perfilActionPerformed

    private void jtxt_nombreUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_nombreUsuarioKeyTyped
        HabilitarButton();
    }//GEN-LAST:event_jtxt_nombreUsuarioKeyTyped

    private void jtxt_apellidoUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_apellidoUsuarioKeyTyped
        HabilitarButton();
    }//GEN-LAST:event_jtxt_apellidoUsuarioKeyTyped

    private void jtxt_telefonoUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_telefonoUsuarioKeyTyped
        HabilitarButton();
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }

    }//GEN-LAST:event_jtxt_telefonoUsuarioKeyTyped

    private void jtxt_correoUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_correoUsuarioKeyTyped
        HabilitarButton();
    }//GEN-LAST:event_jtxt_correoUsuarioKeyTyped

    private void jtxt_dniUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_dniUsuarioKeyTyped
        HabilitarButton();
        char c = evt.getKeyChar();
        if (c < '0' || c > '9')
            evt.consume();
    }//GEN-LAST:event_jtxt_dniUsuarioKeyTyped

    private void jtxt_UsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_UsuarioKeyTyped
        HabilitarButton();

    }//GEN-LAST:event_jtxt_UsuarioKeyTyped

    private void jtxt_contrasenaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_contrasenaKeyTyped
        HabilitarButton();
    }//GEN-LAST:event_jtxt_contrasenaKeyTyped

    private void limpiarRegistroUsuario() {
        jtxt_Usuario.setText("");
        jtxt_nombreUsuario.setText("");
        jtxt_apellidoUsuario.setText("");
        jtxt_correoUsuario.setText("");
        jtxt_contrasena.setText("");
        jtxt_dniUsuario.setText("");
        jtxt_telefonoUsuario.setText("");

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jcbx_perfil;
    private javax.swing.JTextField jtxt_Usuario;
    private javax.swing.JTextField jtxt_apellidoUsuario;
    private javax.swing.JTextField jtxt_contrasena;
    private javax.swing.JTextField jtxt_correoUsuario;
    private javax.swing.JTextField jtxt_dniUsuario;
    private javax.swing.JTextField jtxt_nombreUsuario;
    private javax.swing.JTextField jtxt_telefonoUsuario;
    // End of variables declaration//GEN-END:variables

}
